title:              Wang Peng
email:              1175058131@qq.com
description:        Welcome to My Blog
author:             Wang Peng
baseurl:            ""
url:                ""

# Social Profiles
twitter_username:   
github_username:    DBWp1314
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
